version: '3.3'
services:
  database:
    container_name: database_1
    image: postgres
    volumes:
      - ./sql_sources.sql:/docker-entrypoint-initdb.d/sql_sources.sql
    restart: unless-stopped
    environment:
      POSTGRES_DB: myDb
      POSTGRES_USER: myUser
      POSTGRES_PASSWORD: mypassword1
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "5434:5432"

